# Based on https://medium.com/@littl3miss/use-the-init-container-to-create-kafka-topics-70d7d586152
version: "3.5"
services:
  
 zookeeper:
  image: bitnami/zookeeper
  container_name: zookeeper
  ports:
      - "2181:2181"
  environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_AUTOPURGE_INTERVAL=1
  networks:
      - kafka
      
 kafka:
  image: bitnami/kafka
  container_name: kafka
  ports:
      - 9092:9092
  networks:
      - kafka
  depends_on:
      zookeeper:
        condition: service_started
  environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
  command: bash -c "/opt/bitnami/kafka/bin/kafka-topics.sh --create --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic flight_delay_classification_request"
  command: bash -c "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:9092 --list"
