apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
  namespace: bdfi
spec:
  ports:
    - name: mongodbport
      port: 27017
      targetPort: 27017
  selector:
    app: mongodb

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deploy
  namespace: bdfi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: josemariafrupm/mongodb-bdfi
        ports:
          - containerPort: 27017